### ISSUE TITLE
hover-subject-info URL 解析错误

### ISSUE THREAD

**Issue by Kasper4649** [trim21/bgm-tv-userscripts#4]
# Description
hover-subject-info URL 解析错误

## Environment

- language version:
- app/lib/repo version:

## How to reproduce
[这个链接](https://bgm.tv/group/topic/354866)下会报错

<img width="478" alt="image" src="https://user-images.githubusercontent.com/30112685/193592938-5e22d32b-3f3d-4f59-b1ae-2f56d7e8a2a1.png">
<img width="791" alt="image" src="https://user-images.githubusercontent.com/30112685/193592962-d3244a07-3fe1-42f4-815a-e2bc7cd7ee2d.png">

## Expectations
正常解析 URL
## Actual result
解析失败。定位到原因在于以 # 开头的 href 解析错误，在 `getSubjectID` 函数中添加过滤条件后能够正常运行。
可以不暴力解析所有 a 标签，而是指定 `class="message"` 以及 `class="cmt_sub_content"` 下的 a 标签。

**Comment by trim21** [comment]
更新一下判断的规则应该就好了

**Comment by trim21** [comment]
现在在条目或者超展开页面也启用了，限制`class="message"`会影响别的网页

**Comment by Kasper4649** [comment]
那只需要特殊判断下 # 开头的 href 就行了。
